import type { Category } from '../services/aiCategoryMap';

/**
 * Keyword → category mapping dictionary.
 * Min 40 terms, includes Filipino/Taglish per spec.
 */
const categoryMappings: Record<string, Category> = {
  // ── Food ─────────────────────────────────────────────────────────────────
  lunch: 'food',
  tanghalian: 'food',
  meryenda: 'food',
  merienda: 'food',
  agahan: 'food',
  hapunan: 'food',
  kain: 'food',
  kainan: 'food',
  pagkain: 'food',
  ulam: 'food',
  // Cebuano / Bisaya
  kaon: 'food',
  'kan-on': 'food',
  pamahaw: 'food',
  paniudto: 'food',
  panihapon: 'food',
  painit: 'food',
  pangaon: 'food',
  bahog: 'food',
  // Common meats / proteins / produce — covers "fried chicken", "beef bowl", etc.
  chicken: 'food',
  manok: 'food',
  'fried chicken': 'food',
  'roast chicken': 'food',
  'chicken inasal': 'food',
  inasal: 'food',
  beef: 'food',
  baka: 'food',
  pork: 'food',
  baboy: 'food',
  liempo: 'food',
  lechon: 'food',
  fish: 'food',
  isda: 'food',
  bangus: 'food',
  tilapia: 'food',
  tuna: 'food',
  salmon: 'food',
  shrimp: 'food',
  hipon: 'food',
  itlog: 'food',
  egg: 'food',
  eggs: 'food',
  bacon: 'food',
  hotdog: 'food',
  'hot dog': 'food',
  ham: 'food',
  longganisa: 'food',
  tocino: 'food',
  tapa: 'food',
  spam: 'food',
  sausage: 'food',
  // Filipino dishes
  sisig: 'food',
  bulalo: 'food',
  'kare-kare': 'food',
  karekare: 'food',
  tinola: 'food',
  nilaga: 'food',
  pinakbet: 'food',
  paksiw: 'food',
  ginataan: 'food',
  dinuguan: 'food',
  menudo: 'food',
  caldereta: 'food',
  kaldereta: 'food',
  afritada: 'food',
  mechado: 'food',
  pancit: 'food',
  lumpia: 'food',
  siomai: 'food',
  siopao: 'food',
  dimsum: 'food',
  // Sides / starches
  kanin: 'food',
  'fried rice': 'food',
  'java rice': 'food',
  'garlic rice': 'food',
  sinangag: 'food',
  noodles: 'food',
  pasta: 'food',
  pancake: 'food',
  waffle: 'food',
  // Vegetables / fruits / extras
  vegetable: 'food',
  vegetables: 'food',
  gulay: 'food',
  salad: 'food',
  fruit: 'food',
  fruits: 'food',
  prutas: 'food',
  mango: 'food',
  banana: 'food',
  saging: 'food',
  apple: 'food',
  orange: 'food',
  watermelon: 'food',
  // Snacks / sweets / drinks
  donut: 'food',
  donuts: 'food',
  cake: 'food',
  pastry: 'food',
  cookie: 'food',
  cookies: 'food',
  biscuit: 'food',
  chocolate: 'food',
  candy: 'food',
  chips: 'food',
  popcorn: 'food',
  'ice cream': 'food',
  icecream: 'food',
  yogurt: 'food',
  smoothie: 'food',
  juice: 'food',
  soda: 'food',
  'soft drink': 'food',
  softdrink: 'food',
  tea: 'food',
  beer: 'food',
  alcohol: 'food',
  wine: 'food',
  taho: 'food',
  bibingka: 'food',
  puto: 'food',
  suman: 'food',
  // Restaurant / venue terms
  restaurant: 'food',
  resto: 'food',
  cafe: 'food',
  cafeteria: 'food',
  bakery: 'food',
  bakeshop: 'food',
  panaderia: 'food',
  carinderia: 'food',
  fastfood: 'food',
  'fast food': 'food',
  'food court': 'food',
  baon: 'food',
  meal: 'food',
  meals: 'food',
  brunch: 'food',
  // PH street food / native delicacies
  chicharon: 'food',
  balut: 'food',
  penoy: 'food',
  kwek: 'food',
  'kwek kwek': 'food',
  kwekkwek: 'food',
  betamax: 'food',
  adidas: 'food',
  mami: 'food',
  pandesal: 'food',
  'pan de sal': 'food',
  ensaymada: 'food',
  // Drinks (Cebuano/Tagalog) + softdrinks
  kape: 'food',
  softdrinks: 'food',
  'soft drinks': 'food',
  sago: 'food',
  gulaman: 'food',
  'sago at gulaman': 'food',
  // Generic meat in Tagalog/Cebuano
  karne: 'food',
  sinaing: 'food',
  sinigang: 'food',
  adobo: 'food',
  fishball: 'food',
  isaw: 'food',
  'halo-halo': 'food',
  buko: 'food',
  sorbetes: 'food',
  breakfast: 'food',
  dinner: 'food',
  snack: 'food',
  snacks: 'food',
  coffee: 'food',
  'milk tea': 'food',
  milktea: 'food',
  boba: 'food',
  grocery: 'food',
  groceries: 'food',
  palengke: 'food',
  burger: 'food',
  pizza: 'food',
  rice: 'food',
  food: 'food',
  drink: 'food',
  drinks: 'food',
  eat: 'food',
  ate: 'food',
  // Filipino fast food + chains
  jollibee: 'food',
  mcdo: 'food',
  mcdonalds: 'food',
  'mc do': 'food',
  kfc: 'food',
  chowking: 'food',
  greenwich: 'food',
  mangInasal: 'food',
  'mang inasal': 'food',
  goldilocks: 'food',
  'red ribbon': 'food',
  'max restaurant': 'food',
  shakeys: 'food',
  yellowcab: 'food',
  'yellow cab': 'food',
  'pizza hut': 'food',
  bonchon: 'food',
  starbucks: 'food',
  cbtl: 'food',
  'coffee bean': 'food',
  tims: 'food',
  'tim hortons': 'food',
  dunkin: 'food',
  'dunkin donuts': 'food',
  krispy: 'food',
  'krispy kreme': 'food',
  cocacola: 'food',
  'coca cola': 'food',
  pepsi: 'food',
  'gong cha': 'food',
  gongcha: 'food',
  chatime: 'food',
  serenitea: 'food',
  cha: 'food',
  // Grocery chains
  sm: 'food',
  smmarket: 'food',
  'sm market': 'food',
  smsupermarket: 'food',
  'sm supermarket': 'food',
  puregold: 'food',
  robinsons: 'food',
  'robinsons supermarket': 'food',
  rustans: 'food',
  'rustans supermarket': 'food',
  shopwise: 'food',
  landers: 'food',
  scash: 'food',
  'savemore': 'food',
  waltermart: 'food',
  '7eleven': 'food',
  '7-eleven': 'food',
  '711': 'food',
  ministop: 'food',
  alfamart: 'food',
  familymart: 'food',
  lawson: 'food',

  // ── Transport ─────────────────────────────────────────────────────────────
  pasahe: 'transport',
  sakay: 'transport',
  // Cebuano / Bisaya
  sakyanan: 'transport',
  traysikol: 'transport',
  'multi-cab': 'transport',
  multicab: 'transport',
  habal: 'transport',
  'habal-habal': 'transport',
  habalhabal: 'transport',
  angkas: 'transport',
  joyride: 'transport',
  jeep: 'transport',
  jeepney: 'transport',
  trike: 'transport',
  tricycle: 'transport',
  bus: 'transport',
  mrt: 'transport',
  lrt: 'transport',
  pnr: 'transport',
  motor: 'transport',
  motorcycle: 'transport',
  motorbike: 'transport',
  scooter: 'transport',
  car: 'transport',
  van: 'transport',
  uvexpress: 'transport',
  'uv express': 'transport',
  ferry: 'transport',
  boat: 'transport',
  bangka: 'transport',
  // Ticketed travel — `ticket` defaults to transport because that's the most
  // common context in PH expense logs (bus/train/plane/ferry tickets). The
  // multi-word forms below match before the bare `ticket` so e.g. "bus
  // ticket" is unambiguous.
  ticket: 'transport',
  tickets: 'transport',
  'plane ticket': 'transport',
  'bus ticket': 'transport',
  'train ticket': 'transport',
  'boat ticket': 'transport',
  'ferry ticket': 'transport',
  'mrt ticket': 'transport',
  'lrt ticket': 'transport',
  pamasahe: 'transport',
  plete: 'transport',
  transpo: 'transport',
  flight: 'transport',
  cebupacific: 'transport',
  'cebu pacific': 'transport',
  pal: 'transport',
  airasia: 'transport',
  'air asia': 'transport',
  // Vehicle upkeep
  carwash: 'transport',
  'car wash': 'transport',
  'oil change': 'transport',
  tire: 'transport',
  tires: 'transport',
  registration: 'transport',
  lto: 'transport',
  ltfrb: 'transport',
  grab: 'transport',
  grabcar: 'transport',
  grabbike: 'transport',
  grabtaxi: 'transport',
  fare: 'transport',
  taxi: 'transport',
  uber: 'transport',
  move: 'transport',
  movit: 'transport',
  indrive: 'transport',
  // Vehicles & fuel
  gas: 'transport',
  petrol: 'transport',
  gasoline: 'transport',
  diesel: 'transport',
  fuel: 'transport',
  shell: 'transport',
  petron: 'transport',
  caltex: 'transport',
  phoenix: 'transport',
  seaoil: 'transport',
  'flying v': 'transport',
  totalenergies: 'transport',
  toll: 'transport',
  rfid: 'transport',
  parking: 'transport',
  beep: 'transport',
  ride: 'transport',
  commute: 'transport',

  // ── Bills ─────────────────────────────────────────────────────────────────
  load: 'bills',
  eload: 'bills',
  'e-load': 'bills',
  paload: 'bills',
  prepaid: 'bills',
  postpaid: 'bills',
  // Cebuano / Bisaya — only retain words that actually signal a bill.
  // (Removed `bayranan`/`bayronon`/`abangan` — too generic or wrong sense:
  // `abangan` is Tagalog for "wait for", not "rent".)
  abang: 'bills', // Cebuano: rent
  suga: 'bills',  // Cebuano: light / electric service
  kuryente: 'bills',
  meralco: 'bills',
  veco: 'bills',
  davao_light: 'bills',
  'davao light': 'bills',
  tubig: 'bills',
  maynilad: 'bills',
  manila_water: 'bills',
  'manila water': 'bills',
  internet: 'bills',
  wifi: 'bills',
  'piso wifi': 'bills',
  pisonet: 'bills',
  pldt: 'bills',
  globe: 'bills',
  smart: 'bills',
  sky: 'bills',
  skycable: 'bills',
  converge: 'bills',
  dito: 'bills',
  tnt: 'bills',
  tm: 'bills',
  'sun cellular': 'bills',
  bayad: 'bills',
  bayad_center: 'bills',
  'bayad center': 'bills',
  rent: 'bills',
  upa: 'bills',
  water: 'bills',
  electric: 'bills',
  electricity: 'bills',
  bill: 'bills',
  bills: 'bills',
  subscription: 'bills',
  netflix: 'bills',
  spotify: 'bills',
  youtube: 'bills',
  'youtube premium': 'bills',
  'apple music': 'bills',
  icloud: 'bills',
  'google one': 'bills',
  hbo: 'bills',
  disney: 'bills',
  'disney+': 'bills',
  viu: 'bills',
  iwant: 'bills',
  vivamax: 'bills',
  prime: 'bills',
  'amazon prime': 'bills',
  // Banks (often associated with bill payments / fees)
  bpi: 'bills',
  bdo: 'bills',
  unionbank: 'bills',
  metrobank: 'bills',
  pnb: 'bills',
  landbank: 'bills',
  'security bank': 'bills',
  rcbc: 'bills',
  chinabank: 'bills',
  eastwest: 'bills',
  gcash: 'bills',
  paymaya: 'bills',
  maya: 'bills',
  coins: 'bills',
  'coins.ph': 'bills',
  grabpay: 'bills',
  amortization: 'bills',
  'home credit': 'bills',
  'cash loan': 'bills',
  loan: 'bills',
  utang: 'bills',
  hulog: 'bills',
  insurance: 'bills',
  philhealth: 'bills',
  pagibig: 'bills',
  'pag-ibig': 'bills',
  sss: 'bills',
  // Schooling / tuition (treated as a recurring obligation, not shopping)
  tuition: 'bills',
  'tuition fee': 'bills',
  matricula: 'bills',
  'school fee': 'bills',
  'miscellaneous fee': 'bills',
  // Mortgage / housing
  mortgage: 'bills',
  amortisation: 'bills',

  // ── Health ────────────────────────────────────────────────────────────────
  gamot: 'health',
  medisina: 'health',
  botika: 'health',
  doctor: 'health',
  hospital: 'health',
  pharmacy: 'health',
  medicine: 'health',
  meds: 'health',
  clinic: 'health',
  dental: 'health',
  dentist: 'health',
  checkup: 'health',
  'check-up': 'health',
  consult: 'health',
  consultation: 'health',
  laboratory: 'health',
  lab: 'health',
  // Cebuano / Bisaya
  tambal: 'health',
  espital: 'health',
  ospital: 'health',
  klinika: 'health',
  doktor: 'health',
  // Common medicines / care
  paracetamol: 'health',
  biogesic: 'health',
  alaxan: 'health',
  ibuprofen: 'health',
  decolgen: 'health',
  bioflu: 'health',
  neozep: 'health',
  diatabs: 'health',
  loperamide: 'health',
  prescription: 'health',
  'x-ray': 'health',
  xray: 'health',
  ecg: 'health',
  ultrasound: 'health',
  toothbrush: 'health',
  toothpaste: 'health',
  mouthwash: 'health',
  watsons: 'health',
  mercury: 'health',
  'mercury drug': 'health',
  generika: 'health',
  rose: 'health',
  'rose pharmacy': 'health',
  southstar: 'health',
  vitamins: 'health',
  vitamin: 'health',
  supplement: 'health',
  supplements: 'health',

  // ── Shopping ─────────────────────────────────────────────────────────────
  // NOTE: Generic "buy" verbs (bili, bumili, palit, pamalit, buy, bought,
  // pabili) are intentionally NOT mapped here — they don't imply shopping
  // specifically. ("Bili ako ng pagkain" = food; "palit ko ug ticket" =
  // transport.) They live in DISPLAY_STOP_WORDS in aiCategoryMap.ts so
  // they're stripped from item lists, but they don't drive categorisation.
  damit: 'shopping',
  sapatos: 'shopping',
  // Cebuano / Bisaya — only words specific to retail
  tindahan: 'shopping',
  shopee: 'shopping',
  lazada: 'shopping',
  zalora: 'shopping',
  carousell: 'shopping',
  tiktok: 'shopping',
  'tiktok shop': 'shopping',
  amazon: 'shopping',
  sulat: 'shopping',
  nota: 'shopping',
  clothes: 'shopping',
  shirt: 'shopping',
  tshirt: 'shopping',
  't-shirt': 'shopping',
  pants: 'shopping',
  jeans: 'shopping',
  jacket: 'shopping',
  hoodie: 'shopping',
  shoes: 'shopping',
  sneakers: 'shopping',
  slippers: 'shopping',
  tsinelas: 'shopping',
  mall: 'shopping',
  divisoria: 'shopping',
  tiangge: 'shopping',
  ukay: 'shopping',
  'ukay-ukay': 'shopping',
  ukayukay: 'shopping',
  thrift: 'shopping',
  uniqlo: 'shopping',
  hm: 'shopping',
  'h&m': 'shopping',
  zara: 'shopping',
  bench: 'shopping',
  penshoppe: 'shopping',
  ace: 'shopping',
  'ace hardware': 'shopping',
  miniso: 'shopping',
  daiso: 'shopping',
  jbl: 'shopping',
  ikea: 'shopping',
  'national bookstore': 'shopping',
  nbs: 'shopping',
  'fully booked': 'shopping',
  // Generic shopping terms (only words that genuinely imply retail)
  shop: 'shopping',
  shopping: 'shopping',
  gadget: 'shopping',
  gadgets: 'shopping',
};

export default categoryMappings;

// Maps DB emoji key → display emoji (for use in feed rows, pills, etc.)
export const CATEGORY_EMOJI: Record<string, string> = {
  food: '🍔',
  transport: '🚌',
  shopping: '🛍',
  bills: '⚡',
  health: '❤️',
  others: '📦',
};

// Maps DB category key → tile background colour (matches theme.ts catXxxBg)
export const CATEGORY_TILE_BG: Record<string, string> = {
  // Expense categories
  food: '#FDF6E3',
  transport: '#EEF6FF',
  shopping: '#FFF0F3',
  bills: '#F3EFFF',
  health: '#EFF8F2',
  others: '#F2EFEC',
  // Income categories
  salary: '#EFF8F2',
  allowance: '#EEF6FF',
  freelance: '#F3EFFF',
  business: '#FDF6E3',
  gifts: '#FFF0F3',
  investment: '#E8F6F5',
  default: '#F7F5F2',
};

// Maps DB emoji key → category text color (matches theme.ts)
export const CATEGORY_COLOR: Record<string, string> = {
  // Expense categories
  food: '#C97A20',
  transport: '#3A80C0',
  shopping: '#C0503A',
  bills: '#7A4AB8',
  health: '#2d6a4f',
  others: '#5C5550',
  // Income categories
  salary: '#2d6a4f',
  allowance: '#3A80C0',
  freelance: '#7A4AB8',
  business: '#C97A20',
  gifts: '#C0503A',
  investment: '#1a7a6e',
  default: '#888780',
};

// Default expense categories — DB key + display name. New signups receive
// these via the seed trigger; existing users get them backfilled by migration.
// CategoryScreen uses this list to mark rows non-deletable (only customs
// can be deleted) and to validate uniqueness against new-category names.
export interface DefaultExpenseCategoryDef {
  key: string;
  name: string;
  sortOrder: number;
}

export const DEFAULT_EXPENSE_CATEGORIES: DefaultExpenseCategoryDef[] = [
  { key: 'food', name: 'Food', sortOrder: 0 },
  { key: 'transport', name: 'Transport', sortOrder: 1 },
  { key: 'shopping', name: 'Shopping', sortOrder: 2 },
  { key: 'bills', name: 'Bills', sortOrder: 3 },
  { key: 'health', name: 'Health', sortOrder: 4 },
  { key: 'others', name: 'Others', sortOrder: 5 },
];

/** Set of default expense keys — used to gate the Delete action in CategoryScreen. */
export const DEFAULT_EXPENSE_KEYS: ReadonlySet<string> = new Set(
  DEFAULT_EXPENSE_CATEGORIES.map((c) => c.key),
);

// Income category definitions (used in AddTransactionSheet + FeedScreen)
export interface IncomeCategoryDef {
  key: string;
  name: string;
}

export const INCOME_CATEGORIES: IncomeCategoryDef[] = [
  { key: 'salary', name: 'Salary' },
  { key: 'allowance', name: 'Allowance' },
  { key: 'freelance', name: 'Freelance' },
  { key: 'business', name: 'Business' },
  { key: 'gifts', name: 'Gifts' },
  { key: 'investment', name: 'Investment' },
  { key: 'default', name: 'Others' },
];

/** Set of income keys — used to filter income out of expense-only screens. */
export const INCOME_KEYS: ReadonlySet<string> = new Set(
  INCOME_CATEGORIES.map((c) => c.key),
);
