import { extractItems, buildDisplayName } from '../src/services/aiCategoryMap';

const testCases = [
    // --- FOOD & DINING (1-60) ---
    { text: "jollibee 2pc chickenjoy meal 250 cash", category: "food", surface: "cash" },
    { text: "starbucks iced latte grande 190 gcash", category: "food", surface: "gcash" },
    { text: "grabfood macao imperial milk tea 300 maya", category: "food", surface: "maya" },
    { text: "foodpanda bonchon soy garlic chicken 450 credit_card", category: "food", surface: "credit_card" },
    { text: "kfc bucket of fries and zinger 320 gotyme", category: "food", surface: "gotyme" },
    { text: "dinner at mamou rockwell 3500 bpi", category: "food", surface: "bpi" },
    { text: "kumain sa pares retiro 120 cash", category: "food", surface: "cash" },
    { text: "mcdo bff fries and 2 mcfloat 250 gcash", category: "food", surface: "gcash" },
    { text: "pizzahut hawaiian supreme large 600 unionbank", category: "food", surface: "unionbank" },
    { text: "tim hortons iced capp 170 cash", category: "food", surface: "cash" },
    { text: "binili ng taho sa labas 30 cash", category: "food", surface: "cash" },
    { text: "kwek kwek and fishball sa kanto 50 cash", category: "food", surface: "cash" },
    { text: "samgyupsal sa romance 599 bdo", category: "food", surface: "bdo" },
    { text: "yellow cab charlies chan 450 gcash", category: "food", surface: "gcash" },
    { text: "cbtl white chocolate mocha 210 maya", category: "food", surface: "maya" },
    { text: "mang inasal pm1 with unli rice 150 cash", category: "food", surface: "cash" },
    { text: "chowking chao fan with siomai 110 gcash", category: "food", surface: "gcash" },
    { text: "snr new york style pizza slice 130 gotyme", category: "food", surface: "gotyme" },
    { text: "potato corner mega cheese 120 cash", category: "food", surface: "cash" },
    { text: "army navy burger and freedom fries 380 credit_card", category: "food", surface: "credit_card" },
    { text: "tapa king classic tapa 200 maya", category: "food", surface: "maya" },
    { text: "wendys iced tea and salad 250 gcash", category: "food", surface: "gcash" },
    { text: "burger king whopper meal 290 bpi", category: "food", surface: "bpi" },
    { text: "tokyo tokyo beef misono 220 cash", category: "food", surface: "cash" },
    { text: "shakeys mojos and thin crust 750 unionbank", category: "food", surface: "unionbank" },
    { text: "maxs spring chicken half 350 bdo", category: "food", surface: "bdo" },
    { text: "krispy kreme 1 dozen original glazed 450 gcash", category: "food", surface: "gcash" },
    { text: "dunkin donuts munchkins bucket 300 cash", category: "food", surface: "cash" },
    { text: "mary grace ensaymada and hot choco 400 credit_card", category: "food", surface: "credit_card" },
    { text: "yabu katsu set 550 bpi", category: "food", surface: "bpi" },
    { text: "contis mango bravo slice 250 gcash", category: "food", surface: "gcash" },
    { text: "panda express orange chicken 300 maya", category: "food", surface: "maya" },
    { text: "din tai fung xiao long bao 400 credit_card", category: "food", surface: "credit_card" },
    { text: "mendokoro ramen 500 bdo", category: "food", surface: "bdo" },
    { text: "frankies garclic parmesan wings 450 gcash", category: "food", surface: "gcash" },
    { text: "cibo penne al telefono 550 unionbank", category: "food", surface: "unionbank" },
    { text: "manila peninsula buffet 3500 credit_card", category: "food", surface: "credit_card" },
    { text: "vikings buffet weekend 1200 bpi", category: "food", surface: "bpi" },
    { text: "sambokojin yakiniku 999 gotyme", category: "food", surface: "gotyme" },
    { text: "cabalen eat all you can 500 cash", category: "food", surface: "cash" },
    { text: "binalot adobo and itlog 150 cash", category: "food", surface: "cash" },
    { text: "andoks litson manok 350 gcash", category: "food", surface: "gcash" },
    { text: "chooks to go oven roast 320 maya", category: "food", surface: "maya" },
    { text: "baliwag lechon liempo 380 cash", category: "food", surface: "cash" },
    { text: "angels burger buy 1 take 1 45 cash", category: "food", surface: "cash" },
    { text: "shawarma shack buy 1 take 1 120 gcash", category: "food", surface: "gcash" },
    { text: "turks pita shawarma 100 cash", category: "food", surface: "cash" },
    { text: "siomai house 4pcs with gulaman 70 cash", category: "food", surface: "cash" },
    { text: "master siomai beef 50 cash", category: "food", surface: "cash" },
    { text: "zagu pearl shake 80 gcash", category: "food", surface: "gcash" },
    { text: "coco milk tea 3 brothers 160 maya", category: "food", surface: "maya" },
    { text: "chatime roasted milk tea 140 gotyme", category: "food", surface: "gotyme" },
    { text: "llao llao medium frozen yogurt 190 gcash", category: "food", surface: "gcash" },
    { text: "dairy queen blizzard 120 cash", category: "food", surface: "cash" },
    { text: "gelatissimo 2 scoops 250 credit_card", category: "food", surface: "credit_card" },
    { text: "baskin robbins mint choco 200 bdo", category: "food", surface: "bdo" },
    { text: "jamba juice strawberry wild 220 gcash", category: "food", surface: "gcash" },
    { text: "fruitas buko shake 90 cash", category: "food", surface: "cash" },
    { text: "boost juice all berry bang 250 maya", category: "food", surface: "maya" },
    { text: "pick up coffee iced caramel 85 gcash", category: "food", surface: "gcash" },

    // --- GROCERIES & MARKET (61-120) ---
    { text: "sm supermarket weekly groceries 3500 bpi", category: "grocery", surface: "bpi" },
    { text: "puregold bigas and delata 2000 cash", category: "grocery", surface: "cash" },
    { text: "robinsons supermarket snacks 800 gcash", category: "grocery", surface: "gcash" },
    { text: "landmark makati fruits and veg 1500 credit_card", category: "grocery", surface: "credit_card" },
    { text: "savemore itlog, gatas, tinapay 600 gotyme", category: "grocery", surface: "gotyme" },
    { text: "waltermart meat and poultry 1200 bdo", category: "grocery", surface: "bdo" },
    { text: "rustans fresh premium steaks 4500 credit_card", category: "grocery", surface: "credit_card" },
    { text: "s&r bulk buy toilet paper and frozen food 5000 unionbank", category: "grocery", surface: "unionbank" },
    { text: "landers pizza and snacks 2500 maya", category: "grocery", surface: "maya" },
    { text: "all day supermarket late night run 700 gcash", category: "grocery", surface: "gcash" },
    { text: "palengke isda at gulay 800 cash", category: "grocery", surface: "cash" },
    { text: "bili ng sibuyas at bawang sa talipapa 100 cash", category: "grocery", surface: "cash" },
    { text: "dali everyday grocery chocolates 300 cash", category: "grocery", surface: "cash" },
    { text: "alfamart midnight snack 150 gcash", category: "grocery", surface: "gcash" },
    { text: "711 hotdog and big gulp 90 cash", category: "grocery", surface: "cash" },
    { text: "uncle johns fried chicken 85 gcash", category: "grocery", surface: "gcash" },
    { text: "lawson karage and rice 100 maya", category: "grocery", surface: "maya" },
    { text: "family mart onigiri 75 cash", category: "grocery", surface: "cash" },
    { text: "sari sari store coke 1.5 and ice 95 cash", category: "grocery", surface: "cash" },
    { text: "bumili ng mantika at toyo sa tindahan 50 cash", category: "grocery", surface: "cash" },
    { text: "south supermarket monthly supplies 4000 bpi", category: "grocery", surface: "bpi" },
    { text: "fisher supermaket fresh seafood 1800 gcash", category: "grocery", surface: "gcash" },
    { text: "metro supermarket cebu lechon 1500 bdo", category: "grocery", surface: "bdo" },
    { text: "ever bilena sm hypermarket 500 cash", category: "grocery", surface: "cash" },
    { text: "cherry foodarama baking supplies 900 credit_card", category: "grocery", surface: "credit_card" },
    { text: "merkado supermarket fresh produce 1100 maya", category: "grocery", surface: "maya" },
    { text: "the marketplace wine and cheese 2500 unionbank", category: "grocery", surface: "unionbank" },
    { text: "real food organic veg 1300 credit_card", category: "grocery", surface: "credit_card" },
    { text: "healthy options vitamins and snacks 3000 bpi", category: "grocery", surface: "bpi" },
    { text: "bow and wow dog food 2000 gcash", category: "grocery", surface: "gcash" },
    { text: "pet express cat litter 800 gotyme", category: "grocery", surface: "gotyme" },
    { text: "cartimar pet supplies 1500 cash", category: "grocery", surface: "cash" },
    { text: "farmers market cubao crabs and shrimp 2500 cash", category: "grocery", surface: "cash" },
    { text: "quiapo market fresh flowers 500 cash", category: "grocery", surface: "cash" },
    { text: "divisoria fruits 800 cash", category: "grocery", surface: "cash" },
    { text: "bili ng yelo sa kapitbahay 10 cash", category: "grocery", surface: "cash" },
    { text: "1 sack of rice jasmine 2500 gcash", category: "grocery", surface: "gcash" },
    { text: "mineral water 5 gallons delivery 200 cash", category: "grocery", surface: "cash" },
    { text: "yakult 1 pack sa sm 60 cash", category: "grocery", surface: "cash" },
    { text: "nutella large jar puregold 450 gcash", category: "grocery", surface: "gcash" },
    { text: "spam 3 cans 600 bdo", category: "grocery", surface: "bdo" },
    { text: "corned beef purefoods 250 cash", category: "grocery", surface: "cash" },
    { text: "century tuna flakes in oil 5 cans 200 gcash", category: "grocery", surface: "gcash" },
    { text: "lucky me pancit canton 1 dozen 180 cash", category: "grocery", surface: "cash" },
    { text: "nissin seafood cup noodles 150 maya", category: "grocery", surface: "maya" },
    { text: "bear brand milk powder 1kg 400 gotyme", category: "grocery", surface: "gotyme" },
    { text: "nestcafe stick 1 dozen 100 cash", category: "grocery", surface: "cash" },
    { text: "kopiko brown coffee 80 cash", category: "grocery", surface: "cash" },
    { text: "milo 1kg pack 350 gcash", category: "grocery", surface: "gcash" },
    { text: "quaker oats 1kg 200 bpi", category: "grocery", surface: "bpi" },
    { text: "fita biscuits 1 bucket 150 cash", category: "grocery", surface: "cash" },
    { text: "skyflakes 1 box 120 cash", category: "grocery", surface: "cash" },
    { text: "gardenia classic white bread 85 gcash", category: "grocery", surface: "gcash" },
    { text: "lady's choice mayonnaise 200 maya", category: "grocery", surface: "maya" },
    { text: "eden cheese 1 block 100 cash", category: "grocery", surface: "cash" },
    { text: "magnolia butter salted 150 bdo", category: "grocery", surface: "bdo" },
    { text: "bounty fresh whole chicken 250 gcash", category: "grocery", surface: "gcash" },
    { text: "monterey ground pork 1kg 350 gotyme", category: "grocery", surface: "gotyme" },
    { text: "purefoods hotdog 1kg 300 cash", category: "grocery", surface: "cash" },
    { text: "tokwa at baboy sa palengke 200 cash", category: "grocery", surface: "cash" },

    // --- BILLS & UTILITIES (121-180) ---
    { text: "meralco bill for march 3500 gcash", category: "bills", surface: "gcash" },
    { text: "maynilad water bill 600 maya", category: "bills", surface: "maya" },
    { text: "manila water bill 550 bpi", category: "bills", surface: "bpi" },
    { text: "pldt home fibr internet 1699 credit_card", category: "bills", surface: "credit_card" },
    { text: "globe postpaid plan 1499 bdo", category: "bills", surface: "bdo" },
    { text: "smart signature plan 1999 unionbank", category: "bills", surface: "unionbank" },
    { text: "converge ict internet 1500 gcash", category: "bills", surface: "gcash" },
    { text: "sky cable monthly 1000 credit_card", category: "bills", surface: "credit_card" },
    { text: "cignal tv prepaid load 500 maya", category: "bills", surface: "maya" },
    { text: "netflix premium subscription 549 credit_card", category: "bills", surface: "credit_card" },
    { text: "spotify family plan 214 gcash", category: "bills", surface: "gcash" },
    { text: "youtube premium 159 maya", category: "bills", surface: "maya" },
    { text: "disney plus annual 2990 credit_card", category: "bills", surface: "credit_card" },
    { text: "hbo go monthly 149 bpi", category: "bills", surface: "bpi" },
    { text: "prime video subscription 149 gcash", category: "bills", surface: "gcash" },
    { text: "apple music student 69 credit_card", category: "bills", surface: "credit_card" },
    { text: "icloud 50gb storage 49 gcash", category: "bills", surface: "gcash" },
    { text: "google one 100gb 89 maya", category: "bills", surface: "maya" },
    { text: "condo association dues 2500 unionbank", category: "bills", surface: "unionbank" },
    { text: "apartment rent for april 12000 bdo", category: "bills", surface: "bdo" },
    { text: "pag ibig housing loan 8500 bpi", category: "bills", surface: "bpi" },
    { text: "sss voluntary contribution 1000 gcash", category: "bills", surface: "gcash" },
    { text: "philhealth premium 500 maya", category: "bills", surface: "maya" },
    { text: "maxicare hmo premium 3000 credit_card", category: "bills", surface: "credit_card" },
    { text: "sunlife insurance policy 4500 bpi", category: "bills", surface: "bpi" },
    { text: "prulife uk vul 3000 unionbank", category: "bills", surface: "unionbank" },
    { text: "citibank credit card payment 15000 bdo", category: "bills", surface: "bdo" },
    { text: "bpi express credit bill 8000 bpi", category: "bills", surface: "bpi" },
    { text: "metrobank card bill 5000 gcash", category: "bills", surface: "gcash" },
    { text: "home credit installment 2500 maya", category: "bills", surface: "maya" },
    { text: "spaylater shopee bill 1200 gcash", category: "bills", surface: "gcash" },
    { text: "lazpaylater bill 800 maya", category: "bills", surface: "maya" },
    { text: "gcredit payment 1500 gcash", category: "bills", surface: "gcash" },
    { text: "gloaloan payment 2000 gcash", category: "bills", surface: "gcash" },
    { text: "maya credit payment 1000 maya", category: "bills", surface: "maya" },
    { text: "billease installment 1800 unionbank", category: "bills", surface: "unionbank" },
    { text: "tala loan repayment 2500 gcash", category: "bills", surface: "gcash" },
    { text: "mabilis cash loan 1500 cash", category: "bills", surface: "cash" },
    { text: "car loan rcbc 18000 bpi", category: "bills", surface: "bpi" },
    { text: "motorcycle loan motortrade 3500 cash", category: "bills", surface: "cash" },
    { text: "tuition fee ateneo downpayment 30000 bdo", category: "bills", surface: "bdo" },
    { text: "dlsu tuition installment 20000 unionbank", category: "bills", surface: "unionbank" },
    { text: "ust matriculation fee 15000 bpi", category: "bills", surface: "bpi" },
    { text: "kumon monthly fee 2500 cash", category: "bills", surface: "cash" },
    { text: "anytime fitness gym membership 2500 credit_card", category: "bills", surface: "credit_card" },
    { text: "pound for pound gym 1000 gcash", category: "bills", surface: "gcash" },
    { text: "golf club membership dues 5000 bdo", category: "bills", surface: "bdo" },
    { text: "aws hosting bill 1200 credit_card", category: "bills", surface: "credit_card" },
    { text: "canva pro yearly 2490 paypal", category: "bills", surface: "credit_card" }, // mapping paypal to cc or similar conceptually
    { text: "adobe creative cloud 1500 credit_card", category: "bills", surface: "credit_card" },
    { text: "zoom pro monthly 750 maya", category: "bills", surface: "maya" },
    { text: "chatgpt plus 1100 credit_card", category: "bills", surface: "credit_card" },
    { text: "midjourney sub 550 gcash", category: "bills", surface: "gcash" },
    { text: "github copilot 500 credit_card", category: "bills", surface: "credit_card" },
    { text: "viber out credits 250 gcash", category: "bills", surface: "gcash" },
    { text: "skype credits 300 maya", category: "bills", surface: "maya" },
    { text: "nbi clearance online payment 160 gcash", category: "bills", surface: "gcash" },
    { text: "passport renewal dfa 1200 maya", category: "bills", surface: "maya" },
    { text: "lto car registration renewal 3500 cash", category: "bills", surface: "cash" },
    { text: "prc license renewal 450 gcash", category: "bills", surface: "gcash" },

    // --- TRANSPORT & AUTO (181-240) ---
    { text: "grabcar from qc to makati 450 gcash", category: "transport", surface: "gcash" },
    { text: "angkas from bgc to ortigas 150 cash", category: "transport", surface: "cash" },
    { text: "joyride from pasig to mandaluyong 120 maya", category: "transport", surface: "maya" },
    { text: "move it ride to mall 80 gcash", category: "transport", surface: "gcash" },
    { text: "taxi meter from airport naia 300 cash", category: "transport", surface: "cash" },
    { text: "uv express fx to megamall 50 cash", category: "transport", surface: "cash" },
    { text: "jeepney fare to bayan 13 cash", category: "transport", surface: "cash" },
    { text: "tricycle special sa loob ng village 40 cash", category: "transport", surface: "cash" },
    { text: "mrt ticket taft to north ave 28 cash", category: "transport", surface: "cash" },
    { text: "lrt 1 beep card reload 200 gcash", category: "transport", surface: "gcash" },
    { text: "lrt 2 fare to antipolo 30 cash", category: "transport", surface: "cash" },
    { text: "pnr train ticket to alabang 20 cash", category: "transport", surface: "cash" },
    { text: "edsa carousel bus fare 40 cash", category: "transport", surface: "cash" },
    { text: "p2p bus from trinoma to glorietta 150 gcash", category: "transport", surface: "gcash" },
    { text: "victory liner bus to baguio 800 maya", category: "transport", surface: "maya" },
    { text: "genesis bus to baler 750 cash", category: "transport", surface: "cash" },
    { text: "five star bus to pangasinan 500 cash", category: "transport", surface: "cash" },
    { text: "oceanjet ferry cebu to bohol 800 bpi", category: "transport", surface: "bpi" },
    { text: "2go travel ticket to palawan 2500 credit_card", category: "transport", surface: "credit_card" },
    { text: "cebu pacific flight to boracay 3500 credit_card", category: "transport", surface: "credit_card" },
    { text: "pal flight to davao 4500 bdo", category: "transport", surface: "bdo" },
    { text: "airasia ticket to puerto princesa 2800 unionbank", category: "transport", surface: "unionbank" },
    { text: "petron unleaded gas full tank 2500 credit_card", category: "transport", surface: "credit_card" },
    { text: "shell vpower diesel 1500 gcash", category: "transport", surface: "gcash" },
    { text: "caltex premium gasoline 1000 maya", category: "transport", surface: "maya" },
    { text: "seaoil gas 500 cash", category: "transport", surface: "cash" },
    { text: "phoenix petroleum diesel 800 gotyme", category: "transport", surface: "gotyme" },
    { text: "flying v gas 300 cash", category: "transport", surface: "cash" },
    { text: "autosweep rfid reload 1000 gcash", category: "transport", surface: "gcash" },
    { text: "easytrip rfid load 500 maya", category: "transport", surface: "maya" },
    { text: "slex toll gate cash lane 214 cash", category: "transport", surface: "cash" },
    { text: "nlex toll fee 350 cash", category: "transport", surface: "cash" },
    { text: "cavitex toll 64 cash", category: "transport", surface: "cash" },
    { text: "skyway stage 3 toll 264 gcash", category: "transport", surface: "gcash" },
    { text: "sm mall parking fee flat rate 50 cash", category: "transport", surface: "cash" },
    { text: "ayala triangle parking 150 gcash", category: "transport", surface: "gcash" },
    { text: "bgc high street parking 200 maya", category: "transport", surface: "maya" },
    { text: "naia terminal 3 overnight parking 300 cash", category: "transport", surface: "cash" },
    { text: "car wash boy sa kanto 150 cash", category: "transport", surface: "cash" },
    { text: "express car wash shell 250 gcash", category: "transport", surface: "gcash" },
    { text: "change oil at shell 2500 credit_card", category: "transport", surface: "credit_card" },
    { text: "rapide brake pad replacement 3500 bpi", category: "transport", surface: "bpi" },
    { text: "vulcanizing shop flat tire repair 100 cash", category: "transport", surface: "cash" },
    { text: "motolite car battery new 5500 bdo", category: "transport", surface: "bdo" },
    { text: "motorcycle helmet evo 2500 gcash", category: "transport", surface: "gcash" },
    { text: "bike inner tube replacement 200 cash", category: "transport", surface: "cash" },
    { text: "grab express delivery fee 150 gcash", category: "transport", surface: "gcash" },
    { text: "lalamove lipat bahay truck 1800 maya", category: "transport", surface: "maya" },
    { text: "borzo courier fee 120 cash", category: "transport", surface: "cash" },
    { text: "transportify cargo van 2500 bpi", category: "transport", surface: "bpi" },
    { text: "angkas padala 100 gcash", category: "transport", surface: "gcash" },
    { text: "joyride delivery 90 cash", category: "transport", surface: "cash" },
    { text: "jrs express shipping fee 150 cash", category: "transport", surface: "cash" },
    { text: "lbc padala package 250 gcash", category: "transport", surface: "gcash" },
    { text: "phlpost registered mail 80 cash", category: "transport", surface: "cash" },
    { text: "pedicab fare to palengke 20 cash", category: "transport", surface: "cash" },
    { text: "habal habal sa probinsya 100 cash", category: "transport", surface: "cash" },
    { text: "rent a car vios 1 day 2500 gcash", category: "transport", surface: "gcash" },
    { text: "van rental out of town 5000 bdo", category: "transport", surface: "bdo" },
    { text: "boat ride island hopping 1500 cash", category: "transport", surface: "cash" },

    // --- SHOPPING & PERSONAL CARE (241-280) ---
    { text: "shopee check out damit 800 gcash", category: "shopping", surface: "gcash" },
    { text: "lazada gadget accessories 1200 maya", category: "shopping", surface: "maya" },
    { text: "tiktok shop skincare 500 gotyme", category: "shopping", surface: "gotyme" },
    { text: "zalora nike shoes 4500 credit_card", category: "shopping", surface: "credit_card" },
    { text: "uniqlo basic shirts 2500 bpi", category: "shopping", surface: "bpi" },
    { text: "zara jacket and pants 5500 bdo", category: "shopping", surface: "bdo" },
    { text: "h&m kids clothes 1500 unionbank", category: "shopping", surface: "unionbank" },
    { text: "cotton on shorts 900 gcash", category: "shopping", surface: "gcash" },
    { text: "bench tshirts and underwear 800 cash", category: "shopping", surface: "cash" },
    { text: "penshoppe polo shirt 600 maya", category: "shopping", surface: "maya" },
    { text: "watsons toiletries and vitamins 1800 gcash", category: "shopping", surface: "gcash" },
    { text: "mercury drug medicine and soap 1200 cash", category: "shopping", surface: "cash" },
    { text: "the face shop cleanser 600 bpi", category: "shopping", surface: "bpi" },
    { text: "innisfree sunscreen 800 credit_card", category: "shopping", surface: "credit_card" },
    { text: "mac lipstick 1200 bdo", category: "shopping", surface: "bdo" },
    { text: "sephora makeup haul 4500 credit_card", category: "shopping", surface: "credit_card" },
    { text: "david's salon haircut and treatment 1500 gcash", category: "shopping", surface: "gcash" },
    { text: "bench fix haircut 350 cash", category: "shopping", surface: "cash" },
    { text: "barbershop kanto gupit 100 cash", category: "shopping", surface: "cash" },
    { text: "lay bare waxing 600 maya", category: "shopping", surface: "maya" },
    { text: "let's face it facial 800 gcash", category: "shopping", surface: "gcash" },
    { text: "nail salon mani pedi 500 cash", category: "shopping", surface: "cash" },
    { text: "massage nuat thai 1 hr 450 cash", category: "shopping", surface: "cash" },
    { text: "blind massage sa mall 300 cash", category: "shopping", surface: "cash" },
    { text: "apple store iphone 15 case 2500 credit_card", category: "shopping", surface: "credit_card" },
    { text: "samsung galaxy buds 4000 bdo", category: "shopping", surface: "bdo" },
    { text: "datablitz ps5 game 2500 bpi", category: "shopping", surface: "bpi" },
    { text: "octagon mechanical keyboard 3000 gcash", category: "shopping", surface: "gcash" },
    { text: "cd r king usb flash drive 150 cash", category: "shopping", surface: "cash" },
    { text: "national bookstore school supplies 800 cash", category: "shopping", surface: "cash" },
    { text: "fully booked novel 900 gcash", category: "shopping", surface: "gcash" },
    { text: "sm department store bedsheets 1500 maya", category: "shopping", surface: "maya" },
    { text: "ikea pasay home decor 3500 credit_card", category: "shopping", surface: "credit_card" },
    { text: "mandaue foam pillows 1200 bdo", category: "shopping", surface: "bdo" },
    { text: "true value hardware tools 2000 bpi", category: "shopping", surface: "bpi" },
    { text: "ace hardware lightbulbs 500 gcash", category: "shopping", surface: "gcash" },
    { text: "mr diy random items 400 cash", category: "shopping", surface: "cash" },
    { text: "miniso plushie and tumbler 600 maya", category: "shopping", surface: "maya" },
    { text: "mumuso organizers 300 gcash", category: "shopping", surface: "gcash" },
    { text: "daiso japan 88 pesos items 440 cash", category: "shopping", surface: "cash" },

    // --- INCOME, HEALTH, & ENTERTAINMENT (281-300) ---
    { text: "sweldo 15th bpi payroll 25000 bpi", category: "income", surface: "bpi" },
    { text: "salary end of month 25000 bdo", category: "income", surface: "bdo" },
    { text: "upwork freelance web dev 15000 gcash", category: "income", surface: "gcash" },
    { text: "raket graphic design sideline 5000 maya", category: "income", surface: "maya" },
    { text: "benta ng lumang phone sa greenhills 8000 cash", category: "income", surface: "cash" },
    { text: "cashback from shopback 350 gcash", category: "income", surface: "gcash" },
    { text: "padala galing abroad remittance 10000 cash", category: "income", surface: "cash" },
    { text: "allowance from parents 5000 bpi", category: "income", surface: "bpi" },
    { text: "maya interest earnings 120 maya", category: "income", surface: "maya" },
    { text: "gotyme savings interest 80 gotyme", category: "income", surface: "gotyme" },
    { text: "medical city checkup consultation 1500 gcash", category: "health", surface: "gcash" },
    { text: "st lukes lab tests bloodwork 4500 credit_card", category: "health", surface: "credit_card" },
    { text: "dentist cleaning and pasta 2500 cash", category: "health", surface: "cash" },
    { text: "biogesic and neozep pharmacy 150 cash", category: "health", surface: "cash" },
    { text: "sm cinema imax ticket marvel 700 gcash", category: "entertainment", surface: "gcash" },
    { text: "ayala malls cinemas popcorn combo 450 maya", category: "entertainment", surface: "maya" },
    { text: "timezone load 500 gotyme", category: "entertainment", surface: "gotyme" },
    { text: "quantum arcade tokens 200 cash", category: "entertainment", surface: "cash" },
    { text: "concert ticket sm tickets 8500 credit_card", category: "entertainment", surface: "credit_card" },
    { text: "museum entrance fee national museum 0 cash", category: "entertainment", surface: "cash" }, // Free but valid transaction concept
];

// Execution Loop
testCases.forEach((tc, index) => {
    const i = index + 3; // Starting from 3 to continue your text1 and text2
    console.log(`Text ${i}:`, tc.text);
    console.log(`Items ${i}:`, extractItems(tc.text, { accountSurface: tc.surface }));
    console.log(`Display Name ${i}:`, buildDisplayName(tc.text, tc.category as any, { accountSurface: tc.surface }));
    console.log("-".repeat(40));
});